export { default as authAPI } from './authAPI';
export { default as chatAPI } from './chatAPI';
export { default as gradeAPI } from './gradeAPI';
export { default as resourceAPI } from './resourceAPI';
export { default as revisionAPI } from './revisionAPI';
export { default as studentAPI } from './studentAPI';
export { default as subjectAPI } from './subjectAPI';
export { default as systemAPI } from './systemAPI';
export { default as userAPI } from './userAPI';
